<a href="https://colab.research.google.com/github/tamdoancong/5215-MachineLearning-Doan/blob/master/TamDoanw3_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Download the dataset and uzip it
!wget -O data.zip https://drive.google.com/u/0/uc?id=1DEMhy3x7ws8Eyv0VGzJNFeYkuXhFDXhC&export=download
!unzip -o data.zip 

--2020-09-22 09:31:14--  https://drive.google.com/u/0/uc?id=1DEMhy3x7ws8Eyv0VGzJNFeYkuXhFDXhC
Resolving drive.google.com (drive.google.com)... 108.177.126.102, 108.177.126.138, 108.177.126.113, ...
Connecting to drive.google.com (drive.google.com)|108.177.126.102|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-00-4g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/6m0ers2df8nhgk9hmv6nvfqa59qcj8hh/1600767000000/04063593624032689852/*/1DEMhy3x7ws8Eyv0VGzJNFeYkuXhFDXhC [following]
--2020-09-22 09:31:14--  https://doc-00-4g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/6m0ers2df8nhgk9hmv6nvfqa59qcj8hh/1600767000000/04063593624032689852/*/1DEMhy3x7ws8Eyv0VGzJNFeYkuXhFDXhC
Resolving doc-00-4g-docs.googleusercontent.com (doc-00-4g-docs.googleusercontent.com)... 108.177.119.132, 2a00:1450:4013:c00::84
Connecting to doc-00-4g-docs.googleusercontent.com (doc-00-4g-docs.googleusercontent.co

In [ ]:
#import the libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [ ]:
#load training data
training=pd.read_csv("./data/subject_split/train.csv")
#training

In [ ]:
#label training data
total_training_target=training['total_UPDRS']
motor_training_target=training['motor_UPDRS']

In [ ]:
#load tuning data
tuning=pd.read_csv("./data/subject_split/dev.csv")
#tuning


In [ ]:
#label tuning data
total_tuning_target=tuning['total_UPDRS']
motor_tuning_target=tuning['motor_UPDRS']

In [ ]:
training=training.drop(columns=['subject#','age','sex','test_time','motor_UPDRS','total_UPDRS'])
tuning=tuning.drop(columns=['subject#','age','sex','test_time','motor_UPDRS','total_UPDRS'])

In [ ]:
tuning.columns

Index(['Jitter(%)', 'Jitter(Abs)', 'Jitter:RAP', 'Jitter:PPQ5', 'Jitter:DDP',
       'Shimmer', 'Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'Shimmer:APQ11', 'Shimmer:DDA', 'NHR', 'HNR', 'RPDE', 'DFA', 'PPE'],
      dtype='object')

In [ ]:
training['x0']=1
training=training[['x0','Jitter(%)', 'Jitter(Abs)', 'Jitter:RAP', 'Jitter:PPQ5', 'Jitter:DDP',
       'Shimmer', 'Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'Shimmer:APQ11', 'Shimmer:DDA', 'NHR', 'HNR', 'RPDE', 'DFA', 'PPE']]
training
training.describe#

<bound method NDFrame.describe of       x0  Jitter(%)  Jitter(Abs)  Jitter:RAP  ...     HNR     RPDE      DFA      PPE
0      1    0.00348     0.000022     0.00152  ...  24.885  0.38029  0.62114  0.18399
1      1    0.00563     0.000030     0.00287  ...  21.013  0.45259  0.72558  0.14219
2      1    0.00354     0.000028     0.00168  ...  22.085  0.56362  0.59660  0.18287
3      1    0.00602     0.000046     0.00208  ...  22.663  0.63037  0.69406  0.26387
4      1    0.00414     0.000022     0.00183  ...  21.436  0.55022  0.57203  0.26542
...   ..        ...          ...         ...  ...     ...      ...      ...      ...
2800   1    0.00371     0.000031     0.00147  ...  20.865  0.52891  0.62243  0.20829
2801   1    0.00588     0.000034     0.00306  ...  20.162  0.57128  0.62273  0.26681
2802   1    0.00398     0.000033     0.00199  ...  22.404  0.44357  0.62159  0.16353
2803   1    0.00536     0.000049     0.00214  ...  21.462  0.57086  0.56998  0.23169
2804   1    0.00428     0.00004

In [ ]:
tuning['x0']=1
tuning=tuning[['x0','Jitter(%)', 'Jitter(Abs)', 'Jitter:RAP', 'Jitter:PPQ5', 'Jitter:DDP',
       'Shimmer', 'Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'Shimmer:APQ11', 'Shimmer:DDA', 'NHR', 'HNR', 'RPDE', 'DFA', 'PPE']]
training

x0  Jitter(%)  Jitter(Abs)  Jitter:RAP  ...     HNR     RPDE      DFA      PPE
0      1    0.00348     0.000022     0.00152  ...  24.885  0.38029  0.62114  0.18399
1      1    0.00563     0.000030     0.00287  ...  21.013  0.45259  0.72558  0.14219
2      1    0.00354     0.000028     0.00168  ...  22.085  0.56362  0.59660  0.18287
3      1    0.00602     0.000046     0.00208  ...  22.663  0.63037  0.69406  0.26387
4      1    0.00414     0.000022     0.00183  ...  21.436  0.55022  0.57203  0.26542
...   ..        ...          ...         ...  ...     ...      ...      ...      ...
2800   1    0.00371     0.000031     0.00147  ...  20.865  0.52891  0.62243  0.20829
2801   1    0.00588     0.000034     0.00306  ...  20.162  0.57128  0.62273  0.26681
2802   1    0.00398     0.000033     0.00199  ...  22.404  0.44357  0.62159  0.16353
2803   1    0.00536     0.000049     0.00214  ...  21.462  0.57086  0.56998  0.23169
2804   1    0.00428     0.000047     0.00200  ...  19.554  0.60654  0.63592  0.19203

[2805 rows x 17 columns]

In [ ]:
#convert dataFrame to numpy array
training=training.to_numpy()
total_training_target=total_training_target.to_numpy()
motor_training_target=motor_training_target.to_numpy()
tuning=tuning.to_numpy()
total_tuning_target=total_tuning_target.to_numpy()
motor_tuning_target=motor_tuning_target.to_numpy()
#total_training_target


In [ ]:
#find value W which lead to the least square error
#use numpy.dot
from numpy.linalg import inv

X=training
Y=total_training_target
X_transpose =X.T
X_transposeX = np.dot(X_transpose,X)
X_transposeY = np.dot(X_transpose,Y)
A=inv(X_transposeX)
w=np.dot(A,X_transposeY)
w
#np.matmul(a, b)
#A=np.matmul(X.T,X).shape

#B=inv(A)
#np.matmul(inv(A),X.T).shape


array([ 3.36310981e+01, -2.28181261e+03,  3.00205147e+04, -4.28795911e+04,
        5.54414009e+02,  1.51359371e+04,  5.70114394e+02,  3.33607009e+00,
        5.62994706e+02, -2.38005419e+02, -6.41596375e+00, -4.44278608e+02,
       -1.26918064e+01,  8.57426804e-02,  4.09050293e-01, -9.63485744e+00,
        2.23658562e+01])

In [ ]:
#find value W which lead to the least square error
#use np.matmul(a, b)
X_transposeX = np.matmul(X_transpose,X)
X_transposeY = np.matmul(X_transpose,Y)
A=inv(X_transposeX)
w=np.matmul(A,X_transposeY)
w

array([ 3.36310981e+01, -2.28181261e+03,  3.00205147e+04, -4.28795911e+04,
        5.54414009e+02,  1.51359371e+04,  5.70114394e+02,  3.33607009e+00,
        5.62994706e+02, -2.38005419e+02, -6.41596375e+00, -4.44278608e+02,
       -1.26918064e+01,  8.57426804e-02,  4.09050293e-01, -9.63485744e+00,
        2.23658562e+01])

In [ ]:
np.sqrt(np.mean(np.matmul((np.matmul(X,w) - Y).T , (np.matmul(X,w) - Y))))

505.13989300617703

In [ ]:
#initialize a linear_model.LinearRegression() model with its default parameters,
reg = LinearRegression(fit_intercept=True,normalize=False)

In [ ]:
#train model_3.1 using the fit method, 
# training_subject_ex(not include'total_UPDRS','motor_UPDRS' ) and 
#total_training_subject_ex_targets  which extrcact from "./data/subject_split/train.csv" and group by subject and aggreagate mean, std
reg.fit(training,total_training_target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:

reg.score(tuning, total_tuning_target)


-1.0280801358289389

In [ ]:
#to get the output for  prediction_target_subject_x,tuning_subject_ex is not include'total_UPDRS','motor_UPDRS''subject# 
prediction_target=reg.predict(tuning)

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
#mean_squared_error of model_3.1 :tuning_subject_ex and tuning_targets_subject_ex are extracted from "./data/subject_split/dev.csv" 
#grouby subject and aggregate
#tuning_subject_ex does not include'total_UPDRS','motor_UPDRS''subject' 
reg.score(tuning, total_tuning_target)
mse_model_3_1 =mean_squared_error(total_tuning_target,prediction_target)
mse_model_3_1 

209.89720174648025

In [ ]:
#root mean_squared_error model_3.1 tuning_subject and tuning_targets_subject are extracted from "./data/subject_split/dev.csv" 
#(not include'total_UPDRS','motor_UPDRS''age','sex','test_time' )
np.sqrt(mse_model_3_1 )


14.487829435304663

In [ ]:
reg.coef_


array([ 0.00000000e+00, -2.28181329e+03,  3.00205300e+04, -4.28791383e+04,
        5.54414671e+02,  1.51357863e+04,  5.70114381e+02,  3.33607056e+00,
        5.62994618e+02, -2.38005419e+02, -6.41596375e+00, -4.44278582e+02,
       -1.26918064e+01,  8.57426804e-02,  4.09050293e-01, -9.63485744e+00,
        2.23658562e+01])

In [ ]:
w

array([ 3.36310981e+01, -2.28181261e+03,  3.00205147e+04, -4.28795911e+04,
        5.54414009e+02,  1.51359371e+04,  5.70114394e+02,  3.33607009e+00,
        5.62994706e+02, -2.38005419e+02, -6.41596375e+00, -4.44278608e+02,
       -1.26918064e+01,  8.57426804e-02,  4.09050293e-01, -9.63485744e+00,
        2.23658562e+01])

In [ ]:
X

array([[1.0000e+00, 3.4800e-03, 2.2260e-05, ..., 3.8029e-01, 6.2114e-01,
        1.8399e-01],
       [1.0000e+00, 5.6300e-03, 2.9600e-05, ..., 4.5259e-01, 7.2558e-01,
        1.4219e-01],
       [1.0000e+00, 3.5400e-03, 2.8400e-05, ..., 5.6362e-01, 5.9660e-01,
        1.8287e-01],
       ...,
       [1.0000e+00, 3.9800e-03, 3.3000e-05, ..., 4.4357e-01, 6.2159e-01,
        1.6353e-01],
       [1.0000e+00, 5.3600e-03, 4.8870e-05, ..., 5.7086e-01, 5.6998e-01,
        2.3169e-01],
       [1.0000e+00, 4.2800e-03, 4.6540e-05, ..., 6.0654e-01, 6.3592e-01,
        1.9203e-01]])